FROM golang:1.23.5 as build_sales
ENV GCO_ENABLED 0
ARG BUILD_REF


COPY . /service

# Build the service binary.
WORKDIR /service/api/services/sales
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine.
FROM alpine:3.21
ARG BUILD_DATE
ARG BUILD_REF
RUN addgroup -g 1000 -S sales && \
    adduser -u 1000 -h /service -G sales -S sales
COPY --from=build_sales --chown=sales:sales /service/api/services/sales/sales /service/sales
WORKDIR /service
USER sales
CMD ["./sales"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="William Kennedy <bill@ardanlabs.com>" \
      org.opencontainers.image.source="https://github.com/ardanlabs/service/tree/master/a/services/sales" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Ardan Labs"